version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin 738112235185.dkr.ecr.us-east-1.amazonaws.com/india

  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 738112235185.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 738112235185.dkr.ecr.us-east-1.amazonaws.com/youtube
      - printf '[{"name":"HelloMoz","imageUri":"%s"}]' 738112235185.dkr.ecr.us-east-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
